/* Automatically generated by './build/bin/build-entry.js' */

import Hello from '../components/hello/index.js'
import Layout from '../components/layout/index.js'
import Icon from '../components/icon/index.js'
import IconGroup from '../components/icon-group/index.js'
import IconCompose from '../components/icon-compose/index.js'
import Toolbar from '../components/toolbar/index.js'

const components = [Hello, Layout, Icon, IconGroup, IconCompose, Toolbar]

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component)
  })

  Vue.prototype.$HD_UI = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000,
  }
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  install,
  Hello,
  Layout,
  Icon,
  IconGroup,
  IconCompose,
  Toolbar,
}
